
    # ---- Nginx serve stage ----
    FROM nginx:stable-alpine

    # Copy built React files
    COPY ./matrix_frontend/build /usr/share/nginx/html
    
    COPY ./nginx.conf /etc/nginx/nginx.conf
    
    EXPOSE 80
    
    CMD ["nginx", "-g", "daemon off;"]
    